### ISSUE TITLE
Difference with https://github.com/murtaza64/tree-sitter-groovy ?

### ISSUE THREAD

**Issue by dsully** [amaanq/tree-sitter-groovy#1]
Curious how this differs from https://github.com/murtaza64/tree-sitter-groovy ?

Thanks

**Comment by amaanq** [comment]
I'm not really sure, but the main difference, from what I can tell, is that I extend the Java grammar, whereas the linked one does not, which makes it easier to author the grammar imo (and retains quite a bit of compatibility when working with the Java grammar too). I wrote this up really quickly for something else I was working on, so it's probably not perfect, but works fine for me.
